# Generated by Django 2.1.7 on 2019-06-19 11:03

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatafileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', picklefield.fields.PickledObjectField(editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['updated', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Mxcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
                ('objectives', models.ManyToManyField(to='cycle.Objectives')),
            ],
        ),
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples', models.FileField(blank=True, null=True, upload_to='')),
                ('sampling_method', models.CharField(choices=[('Random', 'Random'), ('Condition', 'Condition'), ('Weights', 'Weights')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sampling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estimated_Population_Exception_Rate', models.IntegerField()),
                ('Tolerable_Exception_Rate', models.IntegerField()),
                ('Population_Size', models.IntegerField()),
                ('Suggested_Sample_Size', models.IntegerField()),
                ('Actual_Sample_Size', models.IntegerField()),
                ('Number_of_Exceptions', models.IntegerField()),
                ('Sample_Exception_Rate', models.IntegerField()),
                ('Computed_Upper_Exception_Rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_of_Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_procedures', models.CharField(max_length=150)),
                ('mxcell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Mxcell')),
            ],
        ),
        migrations.CreateModel(
            name='testing_of_controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('defecient', models.CharField(choices=[('defecient', 'defecient')], max_length=8)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.DatafileModel')),
            ],
        ),
        migrations.AddField(
            model_name='sampling',
            name='control_procedures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Test_of_Controls'),
        ),
        migrations.AddField(
            model_name='samples',
            name='Actual_Sample_Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Actual_Sample_Size', to='cycle.Test_of_Controls'),
        ),
        migrations.AddField(
            model_name='samples',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Client'),
        ),
        migrations.AddField(
            model_name='samples',
            name='control_procedures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Test_of_Controls'),
        ),
        migrations.AddField(
            model_name='samples',
            name='cycle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Cycle'),
        ),
    ]
