# Generated by Django 2.1.7 on 2019-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0002_auto_20190619_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='samples',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
