# Generated by Django 2.1.7 on 2019-06-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0003_samples_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samples',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='samples',
            name='cycle_type',
        ),
        migrations.RemoveField(
            model_name='samples',
            name='year',
        ),
        migrations.AddField(
            model_name='sampling',
            name='Client_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampling',
            name='Cycle_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.Cycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampling',
            name='Year',
            field=models.IntegerField(null=True),
        ),
    ]
