# Generated by Django 2.1.7 on 2019-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0005_auto_20190621_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampling',
            name='control_procedures',
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Computed_Upper_Exception_Rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sampling',
            name='Number_of_Exceptions',
            field=models.IntegerField(null=True),
        ),
    ]
