# Generated by Django 2.1.7 on 2019-07-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0010_deficiency_datafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deficiency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
