# Generated by Django 2.1.7 on 2019-07-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0011_deficiency_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('intro_paragraph', models.TextField(null=True)),
                ('audit_objective', models.TextField(null=True)),
                ('scope_paragraph', models.TextField(null=True)),
                ('deficiency', models.TextField(null=True)),
                ('financials', models.TextField(null=True)),
                ('suggestions', models.TextField(null=True)),
                ('opinion_paragraph', models.TextField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycle.Client')),
            ],
        ),
    ]
