# Generated by Django 2.1.7 on 2019-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0012_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing_of_controls',
            old_name='defecient',
            new_name='deficient',
        ),
    ]
