# Generated by Django 2.1.7 on 2019-07-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0013_auto_20190719_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing_of_controls',
            name='deficient',
            field=models.CharField(choices=[('deficient', 'deficient')], max_length=8),
        ),
    ]
