# Generated by Django 2.1.7 on 2019-07-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0016_auto_20190720_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deficiency',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
