# Generated by Django 2.1.7 on 2019-08-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0019_cycle_in_obj_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlgraph',
            name='cycle_in_obj',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='cycle.Cycle_in_obj'),
            preserve_default=False,
        ),
    ]
