# Generated by Django 2.1.7 on 2019-08-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0020_xmlgraph_cycle_in_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_of_controls',
            name='cycle_in_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.Cycle_in_obj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samples',
            name='sampling_method',
            field=models.CharField(choices=[('Random', 'Random')], max_length=20),
        ),
    ]
