# Generated by Django 2.1.3 on 2019-09-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0021_auto_20190807_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectives',
            name='transaction_objective',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
