# Generated by Django 2.1.3 on 2019-09-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0023_auto_20190918_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cycle_in_obj',
            unique_together={('cycle_type', 'client_name', 'year')},
        ),
    ]
