# Generated by Django 2.1.3 on 2019-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0024_auto_20190920_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.TextField()),
            ],
        ),
    ]
