# Generated by Django 2.1.3 on 2019-09-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycle', '0025_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedures',
            name='activity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='procedures',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cycle.Cycle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedures',
            name='procedure',
            field=models.TextField(null=True),
        ),
    ]
