# Generated by Django 2.1.7 on 2019-08-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ImageField(default='upload_folder/None/no-img.jpg', upload_to='upload_folder/'),
        ),
    ]
