# Generated by Django 2.1.7 on 2019-08-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favorite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='visit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic',
            field=models.ImageField(default='static/upload_folder/None/no-img.jpg', max_length=250, upload_to='static/upload_folder/'),
        ),
    ]
